name: iOS CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app

      - name: Build
        run: |
          xcodebuild clean build \
          -scheme ContactManager \
          -destination 'platform=iOS Simulator,name=iPhone 15' \
          CODE_SIGNING_ALLOWED=NO

      - name: Run Tests
        run: |
          xcodebuild test \
          -scheme ContactManager \
          -destination 'platform=iOS Simulator,name=iPhone 15' \
          CODE_SIGNING_ALLOWED=NO